server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: usuarios-service
          uri: lb://USUARIOS
          predicates:
            - Path=/usuarios/**
  security:
    user:
      password: $2a$12$vTZcFUVNN02ptlcCq0jDGOemMNsxy4jbskE7cnuxS56AUOzlf4x4m

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: teste
  expiration: 3600