server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios
          uri: localhost:8081
          predicates:
            - Path=/usuarios/**
          filters:
            - StripPrefix=1
        - id: usuario_service_swagger_ui
          uri: http://localhost:8081/swagger-ui.html
          predicates:
            - Path=/usuario/swagger-ui.html
          filters:
            - StripPrefix=1
        - id: usuario_service_api_docs
          uri: http://localhost:8081/v3/api-docs
          predicates:
            - Path=/usuario/v3/api-docs
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true