server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: usuario_service_swagger_ui
          uri: http://localhost:8081/swagger-ui/index.html
          predicates:
            - Path=/usuarios/swagger-ui/index.html
          filters:
            - StripPrefix=1
        - id: usuario_service_api_docs
          uri: lb://USUARIOS
          predicates:
            - Path=/usuarios/v3/api-docs
          filters:
              - StripPrefix=1
        - id: teste
          uri: lb://USUARIOS/cadastro-usuario/teste
          predicates:
            - Path=/usuarios/cadastro-usuario/teste
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true