spring:
  application:
    name: gestao

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      name: gestao

  docker:
    compose:
      file: ./gestao/docker-compose.yaml

  datasource:
    url:
    driver-class-name:
    username:
    password:
    hikari:
      schema: gestao
  liquibase:
    change-log: db/changelog/changelog-master.xml

server:
  port: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'
