spring:
  application:
    name: usuarios

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      name: ${spring.application.name}

  docker:
    compose:
      file: ./usuarios/docker-compose.yaml

  datasource:
    url:
    driver-class-name:
    username:
    password:
    hikari:
      schema: ${spring.application.name}
  liquibase:
    change-log: db/changelog/changelog-master.xml

server:
  port: 8081
